name: test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - pyproject.toml
      - 'src/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.version }}
      - run: pdm install --with test
      - run: pdm run pytest
